version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_ENV=production
    restart: unless-stopped
    networks:
      - kleeem-network

networks:
  kleeem-network:
    driver: bridge

